apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: forevigt/hyves-front-end:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              ephemeral-storage: 1Gi
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
