name: Hyves React Front-end
run-name: "${{ github.actor }} ran ${{ github.workflow }} on ${{ github.ref_name }}"

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Pull backend microservice image
      run: |
        docker pull ghcr.io/reviving-hyves/hyves-back-end/auth:latest
    

    - name: Start backend microservice
      run: |
        docker run -d --name backend-service -p 8002:8002 ghcr.io/reviving-hyves/hyves-back-end/auth:latest
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 5433
        DB_USER: usr
        DB_PASSWORD: pswd
        DB_NAME: auth_db

    # Wait for the backend to be ready
    - name: Wait for backend to be ready
      run: |
        until curl -f http://localhost:8002/api; do
          echo "Waiting for backend..."
          sleep 5
        done

    # Start the frontend server
    - name: Start frontend application
      run: npm start &
      env:
        CI: true

    # Run Cypress E2E tests
    - name: Run Cypress E2E tests
      run: npx cypress run
      env:
        CYPRESS_BASE_URL: http://localhost:3000

    # Stop backend container
    - name: Stop backend container
      run: docker stop backend-service && docker rm backend-service
